---
variables:
  RUBY_VERSION_STABLE: "3.2.2"
  RVM_GEMSET: "qat-web-video"
  RVM_COMMAND: "rvm-exec $RUBY_VERSION@$RVM_GEMSET"
  FIREFOX_PATH: "/usr/bin/firefox-quantum"

stages:
  - validation
  - analysis
  - test
  - build
  - deploy
  - release

.ruby:install_stable: &ruby_install_stable
  before_script:
    - rvm install $RUBY_VERSION_STABLE
    - rvm $RUBY_VERSION_STABLE do rvm gemset create $RVM_GEMSET
    - $RVM_COMMAND gem sources --add $NEXUS_GEM_SOURCE_URL
    - $RVM_COMMAND gem install bundler --no-document
    - $RVM_COMMAND gem update bundler --no-document
    - $RVM_COMMAND bundle config mirror.https://rubygems.org https://nexus.readinessit.com/repository/rit-ruby/
    - $RVM_COMMAND bundle config $NEXUS_HOST $NEXUS_USER:$NEXUS_PASS
    - $RVM_COMMAND bundle install
    - $FIREFOX_PATH --version
    - geckodriver --version
    - which Xvfb
    - which ffmpeg

.tags: &tags
  tags:
    - ruby
    - cucumber

.ruby-tests: &ruby_tests
  stage: test
  script:
    - $RVM_COMMAND bundle exec rake qat:devel:tests:run
  coverage: /qa-toolkit\/qat\-web\-video\/test\/coverage. \d+ \/ \d+ LOC \((\d+\.\d+)%\) covered/
  except:
    - develop
    - master
    - tags
  artifacts:
    paths:
      - test/public/index.html
    when: always
    expire_in: 1 day

.ruby_n_tags: &ruby_n_tags
  <<: *ruby_install_stable
  <<: *tags

.ruby-analisys: &ruby_analisys
  <<: *ruby_n_tags
  stage: analysis
  except:
    - master
    - tags

################
## validation ##
################
validation:version:
  <<: *tags
  <<: *ruby_install_stable
  stage: validation
  script:
    - $RVM_COMMAND ruby -e "require './lib/qat/web/video/version'; raise StandardError.new unless Gem::Specification::load('qat-web-video.gemspec').version.to_s == QAT::Web::Video::VERSION"
  except:
    - master
    - tags

validation:existing_tag:
  <<: *tags
  <<: *ruby_install_stable
  stage: validation
  script:
    - $RVM_COMMAND bundle exec rake qat:devel:gitlab:check_version_tags
  except:
    - master
    - tags

##############
## analysis ##
##############
analysis:documentation:
  <<: *ruby_analisys
  script:
    - $RVM_COMMAND bundle exec rake qat:devel:validate_yard_doc
  coverage: /(\d+\.\d+)% documented/
  artifacts:
    paths:
      - doc/
    when: always
    expire_in: 1 day

analysis:static:
  <<: *ruby_analisys
  script:
    - $RVM_COMMAND bundle exec rake qat:devel:static_analysis:html
    - $RVM_COMMAND bundle exec rake qat:devel:static_analysis:validation
  artifacts:
    paths:
      - test/public/rubycritic/
    when: always
    expire_in: 1 day
  allow_failure: true

##########
## test ##
##########
test:ruby-3.2.2:
  <<: *tags
  <<: *ruby_install_stable
  <<: *ruby_tests

###########
## build ##
###########
build:gem:
  <<: *ruby_n_tags
  stage: build
  script:
    - $RVM_COMMAND gem build qat-web-video.gemspec
  artifacts:
    paths:
      - qat-web-video-*.gem
    when: always
    expire_in: 1 day
  only:
    - develop
    - tags

############
## deploy ##
############
deploy:and-test:
  <<: *tags
  stage: deploy
  script:
    - $RVM_COMMAND bundle exec rake qat:web:video:gemfile:example
    - rvm gemset copy $RUBY_VERSION_LATEST@$RVM_GEMSET $RUBY_VERSION_LATEST@$RVM_GEMSET-testing
    - GEM_VERSION=$($RVM_COMMAND ruby -e "puts Gem::Specification::load('qat-web-video.gemspec').version" | tail -1)
    - echo $GEM_VERSION
    - rvm-exec $RUBY_VERSION_LATEST@$RVM_GEMSET-testing gem uninstall qat-web-video --force
    - rvm-exec $RUBY_VERSION_LATEST@$RVM_GEMSET-testing gem install qat-web-video-$GEM_VERSION.gem
    - rm -f Gemfile.lock
    - rvm-exec $RUBY_VERSION_LATEST@$RVM_GEMSET-testing bundle install --full-index --gemfile=Gemfile.example
    - rvm-exec $RUBY_VERSION_LATEST@$RVM_GEMSET-testing bundle exec rake qat:devel:tests:run
  after_script:
    - rvm $RUBY_VERSION_LATEST do rvm gemset delete $RVM_GEMSET-testing --force
  dependencies:
    - build:gem
  except:
    - master
    - tags
  only:
    - develop

#############
## release ##
#############
release:tag:
  <<: *ruby_n_tags
  stage: release
  script:
    - $RVM_COMMAND bundle exec rake qat:devel:gitlab:milestone_tag
  only:
    - master

release:gem:
  <<: *tags
  stage: release
  script:
    - $RVM_COMMAND gem install nexus --no-document
    - $RVM_COMMAND bundle exec gem nexus --url $NEXUS_DEPLOY_URL --credential "${NEXUS_DEPLOY_USER}:${NEXUS_DEPLOY_PASS}" *.gem
  environment:
    name: nexus
    url: https://nexus.readinessit.com/repository/rit-ruby/
  dependencies:
    - build:gem
  only:
    - tags
